# common/tasks/main.yml
- name: Update package cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openjdk-11-jdk
    - wget
    - python3

- name: Set JAVA_HOME
  lineinfile:
    path: ~/.bashrc
    line: "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64"
  register: java_home

- name: Source .bashrc
  command: bash -c "source ~/.bashrc"
  when: java_home.changed

- name: Add hosts to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ item }}"
  loop: "{{ ansible_play_batch }}"

- name: Copy SSH keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  loop: "{{ ansible_play_batch }}"

- name: Create MapR Group
  group:
    name: "{{ mapr_group }}"
    gid: "{{ mapr_group_gid }}"
    state: present
- name: Create MapR User
  user:
    name: "{{ mapr_user }}"
    comment: "MapR default user"
    uid: "{{ mapr_user_uid }}"
    group: "{{mapr_group}}"
    groups: "{{ mapr_group }}"
    password: "{{ mapr_passwd }}"
    createhome: true
    update_password: on_create
    state: present
    append: true
#   groups={{ mapr_group }},root,wheel
- name: Install NTP
  package: name=ntp state=present

# ntp can't start in a container, hence no molecule tests
- name: Start the ntp service
  vars:
    service_Debian: ntp
  service:
    name: "{{ vars['service_' + ansible_os_family] }}"
    state: started
    enabled: true
  tags:
    - skip-docker
    
- name: Install RPC bind
  package: name=rpcbind state=present

# Other actions
- name: Start the RPC bind service
  service: name=rpcbind state=started enabled=yes
  
- name: Install required Ansible package to handle SELinux
  package:
    name: python3-selinux
    state: present
  when: ansible_os_family != 'Suse'



