# playbook.yml

- name: Configure Servers
  hosts: all
  become: yes

  roles:
    - common

- name: Configure MapR Edge Node
  hosts: mapr-edge
  become: yes

  tasks:
    - name: Include vault file
      include_vars:
        file: /home/user2/mapr-cluster/ansible/kms-vault/mykms-store.yml

  roles:
    - mapr-install
